# ARG NODE_VERSION=22.14.0

# FROM node:${NODE_VERSION}-alpine as build
# WORKDIR /app

# COPY package*.json ./
# RUN npm install --legacy-peer-deps

# COPY . .

# FROM node:${NODE_VERSION}-alpine as runtime
# WORKDIR /app

# COPY --from=build /app ./
# # COPY --from=build /app/dist ./dist

# RUN chown -R node:node /app

# USER node
# EXPOSE 3001
# ENV NODE_ENV=production
# CMD ["npm", "start"]

ARG NODE_VERSION=22.14.0

FROM node:${NODE_VERSION} AS build
WORKDIR /app

COPY package*.json ./
RUN npm install --legacy-peer-deps

COPY . .
RUN npm run build

FROM node:${NODE_VERSION}-alpine
WORKDIR /app

RUN npm install -g serve
COPY --from=build /app/dist ./dist

EXPOSE 3001
CMD ["serve", "-s", "dist", "-l", "3001"]
